#!/bin/bash
# Usage, get CCs for a file, stdin, or a sha
set -e

_PATCH=
__cleanup() {
	if [ -n "$_PATCH" ] ; then
		rm -f "$_PATCH"
	fi
}
trap __cleanup INT TERM EXIT
_PATCH=$(mktemp -t get-cc-XXXXXX)

if [ -z "$1" ] ; then
	cat > "$_PATCH"
	PATCH="$_PATCH"
else
	if [ -r "$1" ]; then
		PATCH="$1"
	else
		git format-patch -1 --stdout "$1" > "$_PATCH"
		PATCH="$_PATCH"
	fi
fi

MYSELF=$(git config user.name)
./scripts/get_maintainer.pl \
	--email \
	--git-min-percent 15 \
	--git-since '3-years-ago' \
	--no-rolestats \
	"$PATCH" | grep -vE '^(linux-kernel@vger|'"$MYSELF"')'
