#!/usr/bin/env python3
import os, sys, re
from collections import Counter

# Inspired by:
# git log --since=2020-01-01 | \
# >       grep -E '^    [^ ]*(Signed-off|Tested|Reported|Reviewed|Acked)[^ ]*-by:' | \
# >       cut -d: -f2- |
# >       sed -e 's/^ //g; s/^.*-by: *//g; s/</ </g; s/  / /g; s/>.*/>/g;' | \
# >       sed -e 's/^\([^<]*\)<.*>$/\1/g; s/"\(.*\)"/\1/g' | \
# >       grep -v @syzkaller | \
# >       sort -u

# Find people participating in 50+ commits since 2020-01-01:
# git log --since=2020-01-01 | ~/bin/identity-canonicalizer | sort -g > contributors.txt
# cat contributors.txt | awk '{if ($1 > 2) {print $0}}' >eligible.txt
# cat eligible.txt | awk '{if ($1 > 49) {print $0}}' >ballots.txt

# Find these lines, and keep the email portion
by = re.compile(r'^    [^ ]*(Signed-off|Tested|Reported|Reviewed|Acked)[^ ]*-by:(.*)')
# Split name from email, and remove trailing stuff after email (" # for net/")
trailer = re.compile(r'^(.*)<(.*)>[^>]*$')
# Unwrap quoted names
quoted = re.compile(r'^"(.*)"$')
# Ignore affiliations
affiliated = re.compile(r'^(.*)\(.*\)$')
# Ignore these identities, which are bots.
email_ignore = re.compile(r'^(.*@syzkaller.*.appspot.*|syzkaller@googlegroups\.com|abaci-bugfix@linux.alibaba.com|(lpk|lkp)@intel.com|ci_notify@linaro.org|bot@kernelci.org|patchwork-bot\+.*@kernel.org|keescook\+coverity-bot@chromium.org)$')
# Ignore these names, which may use a "real" email address, but are considered bots.
name_ignore = re.compile(r'^(kernel test robot|coverity-bot)$')
# Ignore one-off typos:
# b88aef36b87c9787a4db724923ec4f57dfd513f3 name/email mismatch
typo_ignore = re.compile(r'^(Zdenek Kabelac <mpatocka@redhat.com>)$')

# Best guess adjustment of names for changes, latinization, abbreviation, and typos.
# match: replacement
spelling = {
		"": None,
		"Ville Syrjala": "Ville Syrjälä",
		"Alexey Budankov": "Alexei Budankov",
		"Yuval Basson": "Yuval Bason",
		"Ricardo Ribalda": "Ricardo Ribalda Delgado",
		"Sean Wang": "Soul Huang",
		"Jernej Skrabec": "Jernej Škrabec",
		"Alexandru M Stan": "Alexandru Stan",
		"Bindu R": "Bindu Ramamurthy",
		"Daniel Almeida": "Daniel W. S. Almeida",
		"Wong, Vee Khee": "Wong Vee Khee",
		"Gabriel C": "Gabriel Craciunescu",
		"Enric Balletbo Serra": "Enric Balletbo i Serra",
		"Yao Lihua": "Lihua Yao",
		"Klaus Jensen": "Klaus Birkelund Jensen",
		"Alex Gagniuc": "Alexandru Gagniuc",
		"Michael Bringmann": "Michael W. Bringmann",
		"Wang Hui": "Hui Wang",
		"Rafael Tinoco": "Rafael David Tinoco",
		"Yi Chen": "Chen Yi",
		"Lee, Shawn C": "Lee Shawn C",
		"Eugeniy Paltsev": "Evgeniy Paltsev",
		"Manish": "Manish Chopra",
		": Phillip Lougher": "Phillip Lougher",
		"Aneesh Kumar": "Aneesh Kumar K.V.",
		"Aneesh Kumar K.V": "Aneesh Kumar K.V.",
		"zhangyi": "Zhang Yi Z",
		"Brad Warrum": "Bradley Warrum",
		"Wang Jian": "Jian Wang",
		"Jose Bollo": "José Bollo",
		"Yu Chen": "Chen Yu",
		"jeffrey.lin": "Jeffrey Lin",
		"Kevin Wangtao": "Tao Wang",
		"Vitaly Mayatskih": "Vitaly Mayatskikh",
		"Oza Oza": "Oza Pawandeep",
		"Sunil Kovvuri Goutham": "Sunil Goutham",
		"Yannick Fertre": "Yannick Fertré",
		"Wilson Chris P": "Chris Wilson",
		"Thomas Hellstrm": "Thomas Hellström",
		"Thomas Hellstrom": "Thomas Hellström",
		"Howard Chung": "Yun-Hao Chung",
		"Pandruvada Srinivas": "Srinivas Pandruvada",
		# Maybe ignore names shorter than 3 chars?
		"sh": "Hui Su",
	   }

email_typos = {
		'mpatocka redhat com': 'mpatocka@redhat.com',
		'eraniangoogle.com': 'eranian@google.com',
		'mgross.linux.intel.com': 'mgross@linux.intel.com',
	      }

def guess_name(name):
	if name == None:
		return None
	if ", " in name:
		name = "%s %s" % tuple(name.split(', ',1))
	name = spelling.get(name, name)
	return name

def flatten(name):
	return name.lower()

class Person:
	def __init__(self, email, name=None):
		self.emails = [email]
		self.names = []
		self.commits = {}

		self.best_count = 0
		self.fullnames = {}
		self.best_name = None

		self.add_name(name)

	def has_name(self):
		if len(self.names) == 0:
			return False
		return True

	def has_email(self, email):
		for known in self.emails:
			if known == email:
				return True
		return False

	# Only for "absorb"
	def get_email(self):
		if len(self.emails) == 1:
			return self.emails[0]
		raise ValueError("Whoops, trying to get email when more than 1 exist: [%s]",
				 "] [".join(self.emails))

	def add_fullname(self, email, name=None):
		if name:
			fullname = "%s <%s>" % (name, email)
		else:
			fullname = '%s' % (email)

		self.fullnames.setdefault(fullname, 0)
		self.fullnames[fullname] += 1
		if self.fullnames[fullname] > self.best_count:
			self.best_name = fullname
			self.best_count = self.fullnames[fullname]

	def add_email(self, email):
		if email not in self.emails:
			self.emails.append(email)

	def add_name(self, name):
		if name:
			self.names.append(name)

	def add_commit(self, sha):
		self.commits.setdefault(sha, 0)
		self.commits[sha] += 1

	# For combining nameless Person
	def add_all_commits(self, other):
		for sha in other.commits:
			self.commits.setdefault(sha, 0)
			self.commits[sha] += other.commits[sha]

	# To find best email address.
	def collapse_aliases(self):
		drop = []
		add = dict()
		for fullname in self.fullnames:
			name = None
			email = fullname
			if '<' in email:
				name, email = fullname.split(' <',1)
				name = name.strip()
				if email.endswith('>'):
					email = email.split('>')[0]
			if '@' not in email:
				raise ValueError("missing @ in: %s" % (fullname))
			user, domain = email.split('@', 1)
			# No +, move on.
			if '+' not in user:
				continue
			# Reconstruct without +... suffix
			user = user.split('+', 1)[0]
			email = "%s@%s" % (user, domain)
			# If this is a novel email, move on.
			if not self.has_email(email):
				continue

			if name:
				collapsed = "%s <%s>" % (name, email)
			else:
				collapsed = '%s' % (email)
			add.setdefault(collapsed, 0)
			add[collapsed] += self.fullnames[fullname]
			drop.append(fullname)
		# Zero out any collapsed entries
		for fullname in drop:
			self.fullnames[fullname] = 0
		# Insert any new counts
		for fullname in add:
			self.fullnames.setdefault(fullname, 0)
			self.fullnames[fullname] += add[fullname]
		# Recount most used full name.
		self.best_name = None
		self.best_count = 0
		for fullname in self.fullnames:
			if self.fullnames[fullname] > self.best_count:
				self.best_name = fullname
				self.best_count = self.fullnames[fullname]

	def dump(self, show_all_emails=False):
		out = "%d\t%s" % (len(self.commits), self.best_name)
		if show_all_emails:
			for fullname in self.fullnames:
				if fullname != self.best_name:
					out += "\n\t%s" % (fullname)
			#for commit in self.commits:
			#	out += "\n\t\t%s" % (commit)
		return out

class Pool:
	def __init__(self):
		self.email_to_person = {}
		self.name_to_person = {}
		self.people = []
		# For debugging collisions.
		self.date = None

	def saw_email(self, person, email):
		person.add_email(email)
		self.email_to_person.setdefault(flatten(email), person)
		return person

	def saw_name(self, person, name):
		if name:
			person.add_email(name)
			self.name_to_person.setdefault(flatten(name), person)
		return person

	def collapse_aliases(self):
		for person in self.people:
			person.collapse_aliases()

	def absorb(self, complete, part):
		# Take all the commits
		complete.add_all_commits(part)
		# Remove old email entry
		email = flatten(part.get_email())
		del self.email_to_person[email]
		# Record email on the complete Person
		self.saw_email(complete, email)
		return complete

	def found(self, sha, email, name=None):
		#if 'dionne@' in email:
		#	print('track: [%s] %s (%s)' % (name, email, sha), file=sys.stderr)
		person = None

		if '@' not in email:
			print("Ignoring email without @ for %s: %s" % (sha, email), file=sys.stderr)
			return

		person_by_email = self.email_to_person.get(flatten(email), None)
		if name:
			person_by_name = self.name_to_person.get(flatten(name), None)
		else:
			person_by_name = None

		if person_by_name and person_by_email:
			# If we find a Person entry with a name, and it has an
			# email conflict with a Person without a name, merge
			# the nameless Person with the named Person.
			if person_by_email != person_by_name and \
			   not person_by_email.has_name() and \
			   not person_by_name.has_email(email):
				#print("Absorbing:\nperson_by_email:\n%s\ninto person_by_name:\n%s" % (person_by_email.dump(show_all_emails=True), person_by_name.dump(show_all_emails=True)), file=sys.stderr)
				self.absorb(person_by_name, person_by_email)
				person_by_email = None
			else:
				person = person_by_email
				# If there are existing people with conflicting details, fail.
				if person_by_email != person_by_name:
					print("%s\nCollided %s (name:[%s] email:%s) on two people:\n%s\n\n%s" % (self.date, sha, name, email, person_by_email.dump(show_all_emails=True), person_by_name.dump(show_all_emails=True)), file=sys.stderr)
					return person

		# If we found a person by email only, add their name.
		if person_by_email and not person_by_name:
			person = self.saw_name(person_by_email, name)

		# If we found a person by name only, add their email.
		if person_by_name and not person_by_email:
			person = self.saw_email(person_by_name, email)

		# If we found a completely new person, create their entry.
		if not person:
			person = Person(email, name)
			self.people.append(person)
			self.saw_email(person, email)
			self.saw_name(person, name)

		# Record this email/name combo.
		person.add_fullname(email, name)
		# Record their activity on this sha.
		person.add_commit(sha)

		return person

	def set_date(self, date):
		self.date = date.strip()

	def dump(self, show_all_emails=False):
		out = []
		for person in self.people:
			out.append(person.dump(show_all_emails))
		return out

pool = Pool()
sha = None
for line in sys.stdin:
	if line.startswith('commit '):
		sha = line.split(' ')[1].strip()
		continue
	if line.startswith('Date: ') or line.startswith('AuthorDate: '):
		pool.set_date(" ".join(line.split(' ')[1:]))
		continue
	hit = by.search(line)
	if not hit:
		continue

	line = hit.group(2).strip()
	hit = trailer.search(line)
	if hit:
		email = hit.group(2).strip()
		name = hit.group(1).strip()

		hit = quoted.search(name)
		if hit:
			name = hit.group(1).strip()
		hit = affiliated.search(name)
		if hit:
			name = hit.group(1).strip()

		name = guess_name(name)
	else:
		email = line
		name = None

	# Ignore various emails.
	hit = email_ignore.search(email)
	if hit:
		continue

	# Replace email typos.
	email = email_typos.get(email, email)

	if name:
		# Ignore various names.
		hit = name_ignore.search(name)
		if hit:
			name = None
		# Skip specific name+email typos.
		hit = typo_ignore.search('%s <%s>' % (name, email))
		if hit:
			continue

	person = pool.found(sha, email, name)

# Post-process to collapse "+"s in email aliases
pool.collapse_aliases()

full = False
if len(sys.argv) > 1:
	if sys.argv[1] == '--full':
		full = True

print("\n".join(pool.dump(full)))
