#!/bin/bash
set -e
#
# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

BASE=""
remote="$1"
url="$2"
echo >&2 "pre-push: $remote $url"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

# Consume stdin
while read local_ref local_oid remote_ref remote_oid
do
	branch="${local_ref#refs/heads/}"
#	continue # do nothing
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		echo >&2 "pre-push: Deleting branch."
	else
		if [ -z "$PUSH_SINCE_TAG" ]; then
			linus_since=$(git describe --match 'v*' --abbrev=0 $local_oid)
			echo >&2 "pre-push: Most recent release tag:    $linus_since"
		else
			linus_since="$PUSH_SINCE_TAG"
			echo >&2 "pre-push: PUSH_SINCE_TAG override:    $linus_since"
		fi
		since="$linus_since"

		next_since=$(git describe --match 'next-*' --abbrev=0 $local_oid 2>/dev/null || true)
		if [ -n "$next_since" ] ; then
			echo >&2 "pre-push: Most recent linux-next tag: $next_since"

			commits_from_linus=$(git rev-list --count ${linus_since}..${local_oid})
			commits_from_next=$(git rev-list --count ${next_since}..${local_oid})

			if [ "$commits_from_linus" -gt "$commits_from_next" ]; then
				since="$next_since"
			fi
			echo >&2 "pre-push: Using nearer tag as base:   $since"
		fi

		# If we have a new branch, or if the remote HEAD is not an
		# ancestor of the local HEAD, we're probably doing a --force,
		# so we need to treat it as if we're pushing a new branch.
		if test "$remote_oid" = "$zero" || \
		   ! git merge-base --is-ancestor $remote_oid $local_oid
		then
			# New branch, examine all commits since most recent tag.
			range="$since..$local_oid"
			echo >&2 "pre-push: New branch. Want to check:  $range"
		else
			# Update to existing branch, examine new commits

			# If we're pushing an updated branch we either
			# have a few new commits to check or we've done
			# a merge and push, in which case we want to only
			# check since the last tag. If $remote_oid is
			# contained by the $since tag, only check since
			# that tag.
			if git merge-base --is-ancestor $remote_oid $since ; then
				range="$since..$local_oid"
				echo >&2 "pre-push: Merged branch. Want to check: $range"
			else
				range="$remote_oid..$local_oid"
				echo >&2 "pre-push: Existing branch. Want to check: $range"
			fi
		fi
		~/bin/check_commits "$branch" "$range"

		## Check for WIP commit
		#commit=$(git rev-list -n 1 --grep '^WIP\b' "$range")
		#if test -n "$commit"
		#then
		#	echo >&2 "Found WIP commit in $local_ref, not pushing"
		#	exit 1
		#fi
	fi
	#echo >&2 "$local_ref"
	echo >&2 "$branch"
done

# Refresh TOTP, if needed.
if echo "$url" | grep -q kernel.org ; then
	if ! ssh git@gitolite.kernel.org 2fa isval >/dev/null; then
		echo -n "Enter TOTP token: "
		stty -F /dev/tty -echo
		read token </dev/tty
		# Show the line feed
		echo ""
		stty -F /dev/tty echo
		ssh git@gitolite.kernel.org 2fa val "$token"
	fi
fi

exit 0
