#!/bin/bash
# Look for a given text; if exactly one is found, launch editor there.
# If more than one is found, allow the user to choose which one to
# open.
set -e
out=$(mktemp -t git-vgrep-XXXXXX)
trap "rm -f $out" EXIT
git grep -n "$@" > "$out"

lines=$(cat "$out" | wc -l)

if [ $lines -eq 0 ]; then
	exit 1
fi

if [ $lines -ne 1 ] ; then
	cat -b "$out"
	read -p 'Choose line: ' line
	LINE=$(awk "NR==$line" "$out")
	echo "$LINE" > "$out"
fi

file=$(cut -d: -f1 "$out")
line=$(cut -d: -f2 "$out")
$EDITOR +"$line" "$file"

